version: "3.7"
services:
  database:
    image: mysql:8
    container_name: vibraxporto_db
    restart: always
    ports:
      - 3306:3306
    environment:
      - MYSQL_USER=docker
      - MYSQL_PASSWORD=123
      - MYSQL_DATABASE=vibraportoseguro
      - MYSQL_ROOT_PASSWORD=321
  app:
    build: .
    container_name: vibraxporto_api
    ports:
      - 3333:3333
      - 9229:9229
    volumes:
      - .:/usr/src/vibra-back
    links:
      - database
    depends_on:
      - database
